CONFIG = {
    "fm_1_feature_cols": [
        "Cu_oreth",
        "Ni_oreth",
        "Ore_mass",
        "Mass_1",
        "Dens_1",
        "Cu_1C",
        "Ni_1C",
    ],
    "fm_1_target_cols": ["Ni_1C_min", "Ni_1C_max", "Cu_1C_min", "Cu_1C_max"],
    "fm_2_feature_cols": [
        "Mass_2",
        "Dens_2",
        "Cu_2F",
        "Ni_2F",
        "Cu_2C",
        "Ni_2C",
        "Cu_2T",
        "Ni_2T",
    ],
    "fm_2_target_cols": ["Cu_2T_min", "Cu_2T_max"],
    "fm_3_feature_cols": [
        "Mass_3",
        "Dens_3",
        "Cu_3F",
        "Ni_3F",
        "Cu_3C",
        "Ni_3C",
        "Cu_3T",
        "Ni_3T",
    ],
    "fm_3_target_cols": ["Cu_3T_min", "Cu_3T_max"],
    "fm_2_3_feature_cols": [
        "Mass",
        "Dens",
        "Cu_F",
        "Ni_F",
        "Cu_C",
        "Ni_C",
        "Cu_T",
        "Ni_T",
        "fm",
    ],
    "fm_2_3_target_cols": ["Cu_T_min", "Cu_T_max"],
    "fm_4_feature_cols": [
        "Mass_4",
        "Vol_4",
        "Dens_4",
        "Cu_4F",
        "Ni_4F",
        "Ni_4C",
        "Ni_4T",
    ],
    "fm_4_target_cols": ["Ni_4C_min", "Ni_4C_max", "Ni_4T_min", "Ni_4T_max"],
    "fm_5_feature_cols": [
        "Mass_5",
        "Vol_5",
        "Dens_5",
        "Ni_5F",
        "Ni_5C",
        "Ni_5T",
    ],
    "fm_5_target_cols": ["Ni_5C_min", "Ni_5C_max", "Ni_5T_min", "Ni_5T_max"],
    "fm_6_feature_cols": [
        "Mass_6",
        "Vol_6",
        "Dens_6",
        "Ni_6F",
        "Ni_6C",
        "Ni_6T",
    ],
    "fm_6_target_cols": ["Ni_6C_min", "Ni_6C_max", "Ni_6T_min", "Ni_6T_max"],
    "fm_4_5_6_feature_cols": [
        "Mass",
        "Vol",
        "Dens",
        "Cu_F",
        "Ni_F",
        "Ni_C",
        "Ni_T",
        "fm",
    ],
    "fm_4_5_6_target_cols": ["Ni_C_min", "Ni_C_max", "Ni_T_min", "Ni_T_max"],
}
