CONFIG = {
    "fm_1_feature_cols": [
        "Cu_oreth",
        "Ni_oreth",
        "Ore_mass",
        "Mass_1",
        "Dens_1",
        "Cu_1C",
        "Ni_1C",
    ],
    "fm_1_target_cols": ["Ni_1C_min", "Ni_1C_max", "Cu_1C_min", "Cu_1C_max"],
    "fm_2_feature_cols": [
        "Mass_2",
        "Dens_2",
        "Cu_2F",
        "Ni_2F",
        "Cu_2C",
        "Ni_2C",
        "Cu_2T",
        "Ni_2T",
    ],
    "fm_2_target_cols": ["Cu_2T_min", "Cu_2T_max"],
    "fm_3_feature_cols": [
        "Mass_3",
        "Dens_3",
        "Cu_3F",
        "Ni_3F",
        "Cu_3C",
        "Ni_3C",
        "Cu_3T",
        "Ni_3T",
    ],
    "fm_3_target_cols": ["Cu_3T_min", "Cu_3T_max"],
    "fm_2_3_feature_cols": [
        "Mass",
        "Dens",
        "Cu_F",
        "Ni_F",
        "Cu_C",
        "Ni_C",
        "Cu_T",
        "Ni_T",
        "fm",
    ],
    "fm_2_3_target_cols": ["Cu_T_min", "Cu_T_max"],
}
